server:
  port: 8001
spring:
  profiles:
    active: prov
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mine.financial.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log.xml
  level:
    com.lucifer.springboot.cache.mapper: debug